services:
  api:
    build: .

    ports: 
      - "3000:3000"
    
    environment:
      - PORT=3000
      - NODE_ENV=development

      - DB_URL=mongodb://mongo:27017/blog-api 
      - JWT_SECRET=your-super-secret-jwt-key-that-is-long
      - JWT_EXPIRES_IN=90d

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: