services:
  api:
    env_file:
    - ../.env

    build: .

    ports: 
      - "3000:3000"
    
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}

      - DB_URL=${TEST_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: